# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('link_url', models.CharField(max_length=255, unique=True)),
                ('page_data', models.CharField(max_length=255, unique=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_crawled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinksQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextword.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_crawled', models.BooleanField(default=False)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextword.Links')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='last_crawled_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextword.Links'),
        ),
    ]
